### ISSUE TITLE
Incorrect build/run instructions for Listing2

### ISSUE THREAD

**Issue by magnus-ekman** [essentialsofparallelcomputing/Chapter2#1]
In the main Readme file, under the heading "Listing2", it says to "Change into the Listing1 directory". I believe that it should be "Change into the Listing2 directory".

Further, it says to do "make ctest -R commit or make commit_tests". I think you first need to do "cmake .", so it should be "cmake . make ctest -R commit or make commit_tests".

It would also be more readable if these commands were on their own lines and formatted as code.

(These are obviously minor issues, but I suspect that you want to make these examples as correct as possible.)

**Comment by scrobey** [comment]
Corrected README instructions and fixed formatting for issue reported by @magnus-ekman with ffbdab998e5a8500eb2ee684ad87f21bce4baf48 commit.
